# Upstream-style partition (calamares type:any) — QEMU virtio /dev/vda compatible.
---
efi:
    mountPoint: "/boot/efi"
    recommendedSize: 300MiB
    minimumSize: 32MiB
    label: "EFI"

defaultFileSystemType: "ext4"
initialPartitioningChoice: none
defaultPartitionTableType: "gpt"
userSwapChoices:
    - none

luksGeneration: luks1
enableLuksAutomatedPartitioning: true
createHybridBootloaderLayout: true

devices:
    type: any
    ignore:
      - /^loop/
      - /^fd/
      - /^sr/
      - /^zram/
      - /^nbd/
