[workspace]
resolver = "2"
members = [
    "strawwu-bridge",
    "strawwu-runtime",
    "strawwu-cli",
    "strawwu-launcher",
    "strawwu-nt",
    "strawwu-graphics",
    "strawwu-audio",
    "strawwu-anticheat",
    "strawwu-device-proxy",
    "strawwu-app-registry",
]

[workspace.package]
version = "0.7.1-preview.22"
edition = "2021"
license = "MIT"
