[workspace]
resolver = "2"
members = [
    "strawwu-bridge",
    "strawwu-runtime",
    "strawwu-launcher",
    "strawwu-nt",
    "strawwu-graphics",
    "strawwu-audio",
    "strawwu-anticheat",
    "strawwu-device-proxy",
]

[workspace.package]
version = "0.4.1-preview.4"
edition = "2021"
license = "MIT"
