#!/usr/bin/env python3
"""
fstab — Simple Calamares Python job that generates /etc/fstab in the target.
Replaces the complex system fstab module which expects specific GS formats
from the C++ partition ViewStep.
"""
import os
import libcalamares


def run():
    gs = libcalamares.globalstorage
    root_mp = gs.value("rootMountPoint")
    partitions = gs.value("partitions")

    if not root_mp:
        return ("fstab: rootMountPoint not set", "")
    if not partitions:
        return ("fstab: no partitions in GlobalStorage", "")

    fstab_path = os.path.join(root_mp, "etc", "fstab")
    os.makedirs(os.path.dirname(fstab_path), exist_ok=True)

    lines = ["# /etc/fstab — generated by StrawWU installer"]
    for p in partitions:
        device = p.get("device", "")
        uuid = p.get("uuid", "")
        mp = p.get("mountPoint", "")
        fs = p.get("fs", "")
        options = p.get("options", "defaults")

        if not mp or not fs:
            continue

        if fs == "fat32":
            fs = "vfat"

        dev_spec = f"UUID={uuid}" if uuid else device
        dump = "0"
        fsck = "1" if mp == "/" else ("2" if mp != "swap" else "0")

        lines.append(f"{dev_spec}\t{mp}\t{fs}\t{options}\t{dump}\t{fsck}")

    lines.append("")
    content = "\n".join(lines)

    with open(fstab_path, "w") as f:
        f.write(content)

    libcalamares.utils.debug(f"fstab: wrote {fstab_path} with {len(partitions)} entries")
    return None
