---
efiBootLoader: "grub"
kernel: "/vmlinuz"
img: "/initrd.img"
grubInstall: "grub-install"
grubMkconfig: "grub-mkconfig"
grubCfg: "/boot/grub/grub.cfg"
efiBootloaderId: "StrawWU"
installEFIFallback: true
