---
defaultGroups:
    - users
    - sudo
    - audio
    - video
    - plugdev
    - netdev
doAutologin: true
autologinGroup: autologin
setRootPassword: false
passwordRequirements:
    minLength: 1
    maxLength: -1
